services:
  - type: web
    name: atlas-api
    env: node
    region: oregon
    plan: standard
    buildCommand: npm install && npm run build:server
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        value: https://atlas-api-fdlq.onrender.com
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://atlas-dashboard-t8rh.onrender.com
      - key: MICROSOFT_CLIENT_ID
        value: 677e4d60-4fe6-4a09-971d-71f96f954759
      - key: MICROSOFT_TENANT_ID
        value: 1c1424b3-9780-4da3-85d1-9c818609d74a
      - key: MICROSOFT_REDIRECT_URI
        value: https://atlas-api-fdlq.onrender.com/api/outlook/callback
      - key: MICROSOFT_CLIENT_SECRET
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: NODE_OPTIONS
        value: --dns-result-order=ipv4first --max-old-space-size=1024
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false

  - type: web
    name: atlas-dashboard
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://atlas-api-fdlq.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
